### ISSUE TITLE
[CI/CD] Build a CI/CD Process

### ISSUE THREAD

**Issue by zhengh96** [dptech-corp/Uni-Dock-Dev#4]
Please build the CI/CD process based on github workflow and keep it available:
- Run unit tests and integration tests every time a Pull Request is submitted to the main branch;
- Automatically compile new executable files after merging Pull Requests.

**Comment by zhengh96** [comment]
The current CI workflow seems to remain some problems... https://github.com/dptech-corp/Uni-Dock/actions/runs/7649647294/job/20941947343?pr=65

**Comment by caic99** [comment]
> I am not sure if we have a machine with GPU as CI/CD runner? @YNYuan @caic99

We have a self-hosted runner with NVIDIA T4 GPU. Please check at: https://github.com/dptech-corp/Uni-Dock/actions/runners?tab=self-hosted

**Comment by caic99** [comment]
> * Automatically compile new executable files after merging Pull Requests.

@zhengh96 Any ideas on where to publish the executables?

**Comment by dp-yuanyn** [comment]
> Please build the CI/CD process based on github workflow and keep it available:
> 
> * Run unit tests and integration tests every time a Pull Request is submitted to the main branch;
> * Automatically compile new executable files after merging Pull Requests.

All done in https://github.com/dptech-corp/Uni-Dock-Dev/pull/25

**Comment by dp-yuanyn** [comment]
> Please build the CI/CD process based on github workflow and keep it available:
> 
> * Run unit tests and integration tests every time a Pull Request is submitted to the main branch;
> * Automatically compile new executable files after merging Pull Requests.

Finished in https://github.com/dptech-corp/Uni-Dock-Dev/pull/25
Pull-requests to main branch will start unitests on unidock/unidock_tools and application e2e tests on unidock_tools.
After prs merged to main branch, docker image will be build and push automatically.
